ARG ROS_DISTRO="jazzy"
FROM osrf/ros:$ROS_DISTRO-desktop-full
ARG BRANCH="ros2"

RUN cat > /root/.entrypoint <<'EOF'
echo -e "\033[1;36m ====="
echo "     _               _                  _"
echo "    | |             | |                (_)"
echo "  __| |  ___    ___ | | __  ___  _ __   _  _ __ ___    __ _   __ _   ___"
echo " / _\` | / _ \\  / __|| |/ / / _ \\| '__| | || '_ \` _ \\  / _\` | / _\` | / _ \\"
echo "| (_| || (_) || (__ |   < |  __/| |    | || | | | | || (_| || (_| ||  __/"
echo " \\__,_| \\___/  \\___||_|\\_\\ \\___||_|    |_||_| |_| |_| \\__,_| \\__, | \\___|"
echo "                                                              __/ |"
echo "                                                             |___/"
echo -e "\033[0m"
echo -e "\033[1;32m\n =====\033[0m"
echo -e "\033[1;32m 👋 Hi! This is Docker virtual environment for DAVE\033[0m"
echo -e "\033[1;33m\tROS2 Jazzy - Gazebo Harmonic (w ardupilot(ardusub) + mavros)\n\033[0m"
EOF

RUN echo 'bash /root/.entrypoint' >> /root/.bashrc
WORKDIR /root
