ARG ROS_DISTRO="jazzy"
FROM osrf/ros:$ROS_DISTRO-desktop-full
ARG BRANCH="ros2"


RUN touch /root/.entrypoint && printf '\033[1;36m =====\n' >> /root/.entrypoint && \
    printf '     _               _                  _                                \n' >> /root/.entrypoint && \
    printf '    | |             | |                (_)                               \n' >> /root/.entrypoint && \
    printf '  __| |  ___    ___ | | __  ___  _ __   _  _ __ ___    __ _   __ _   ___ \n' >> /root/.entrypoint && \
    printf ' / _` | / _ \  / __|| |/ / / _ \| '__| | || '_ ` _ \  / _` | / _` | / _ \\n' >> /root/.entrypoint && \
    printf '| (_| || (_) || (__ |   < |  __/| |    | || | | | | || (_| || (_| ||  __/\n' >> /root/.entrypoint && \
    printf ' \__,_| \___/  \___||_|\_\ \___||_|    |_||_| |_| |_| \__,_| \__, | \___|\n' >> /root/.entrypoint && \
    printf '                                                              __/ |      \n' >> /root/.entrypoint && \
    printf '                                                             |___/       \n\033[0m' >> /root/.entrypoint && \
    printf '\033[1;32m\n =====\n\033[0m' >> /root/.entrypoint && \
    printf "\\033[1;32m 👋 Hi! This is Docker virtual environment for DAVE\n\\033[0m" \
    >> /root/.entrypoint && \
    printf "\\033[1;33m\tROS2 Jazzy - Gazebo Harmonic (w ardupilot(ardusub) + mavros)\n\n\\033[0m" \
    >> /root/.entrypoint && \
    echo 'cat /root/.entrypoint' >> /root/.bashrc

WORKDIR /root
